"""Spectroscopy export via xmgrace.

Writes a Grace project file (``.agr``) directly, then drives the locally
installed ``xmgrace`` binary in ``-hardcopy`` mode to render PNG and EPS, and
finally calls ``ps2pdf`` to produce a PDF. All three artefacts (``.agr``,
``.png``, ``.pdf``) are kept side by side so the user can re-edit the source
in xmgrace later.

Why .agr is hand-written instead of going through the GUI: ``xmgrace
-hardcopy`` only renders an existing .agr file; it does not synthesize one
from raw data. The .agr format is plain text and well documented in
``Default.agr`` shipped with Grace 5.1; we replicate just the subset needed
for a publication-quality multi-channel line plot. Helvetica is set as the
default font (font index 4 in the standard Grace font map).
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional, Sequence

import numpy as np


# ── Font / colour mapping (matches Default.agr from Grace 5.1) ──────────────

# Helvetica family lives at indices 4..7. We use plain Helvetica (4) by
# default; bold variants are 6/7. Times-Roman (0) is the Grace built-in
# default, but the requested default for ProbeFlow exports is Helvetica.
_FONT_HELVETICA       = 4
_FONT_HELVETICA_BOLD  = 6

# Curve colour cycle (indices into the standard Grace colormap).
# 1=black, 2=red, 4=blue, 15=green4, 8=violet, 11=orange, 9=cyan, 13=maroon.
_CURVE_COLORS = (1, 2, 4, 15, 8, 11, 9, 13)


# ── Public types ─────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class Curve:
    """One y-trace in a Grace export."""
    name: str
    y: np.ndarray
    legend: str = ""


# ── Implementation ───────────────────────────────────────────────────────────

def _grace_escape(text: str) -> str:
    """Escape characters that have meaning in Grace string literals.

    Grace strings are wrapped in double quotes; backslashes start formatting
    escapes (\\f, \\1, \\u, …). Plain text in axis labels rarely needs more
    than escaping the quote and backslash characters.
    """
    return (text.replace("\\", "\\\\")
                .replace('"', '\\"'))


def build_agr(
    x: np.ndarray,
    curves: Sequence[Curve],
    *,
    x_label: str,
    y_label: str,
    title: str = "",
    subtitle: str = "",
    font: str = "Helvetica",
    width_pts: int = 792,
    height_pts: int = 612,
) -> str:
    """Compose a Grace .agr project file as a text string.

    Parameters
    ----------
    x:
        1-D x-axis values (shared by all curves).
    curves:
        Iterable of :class:`Curve` — at least one.
    x_label, y_label:
        Axis labels (rendered through Grace formatting; we don't try to
        translate matplotlib mathtext, just plain strings).
    title, subtitle:
        Optional graph titles.
    font:
        Family name. ``"Helvetica"`` (the default) maps to Grace font 4;
        ``"Times-Roman"`` maps to font 0. Anything else falls back to
        Helvetica with no warning.
    """
    if font.lower().startswith("times"):
        font_idx, font_bold_idx = 0, 2
    else:
        font_idx, font_bold_idx = _FONT_HELVETICA, _FONT_HELVETICA_BOLD

    if not curves:
        raise ValueError("xmgrace export needs at least one curve")
    if x.ndim != 1:
        raise ValueError(f"x must be 1-D, got shape {x.shape}")

    # Axis ranges with a small padding so points don't sit on the spines.
    xmin, xmax = float(np.nanmin(x)), float(np.nanmax(x))
    if xmax <= xmin:
        xmax = xmin + 1.0
    ys = np.concatenate([np.asarray(c.y, dtype=float).ravel() for c in curves])
    ys = ys[np.isfinite(ys)]
    if ys.size == 0:
        ymin, ymax = 0.0, 1.0
    else:
        ymin, ymax = float(np.nanmin(ys)), float(np.nanmax(ys))
        if ymax <= ymin:
            ymax = ymin + 1.0
    pad_x = (xmax - xmin) * 0.02
    pad_y = (ymax - ymin) * 0.05
    xmin -= pad_x; xmax += pad_x
    ymin -= pad_y; ymax += pad_y

    # ── Header / canvas ──────────────────────────────────────────────────────
    out: list[str] = []
    out.append("# Grace project file")
    out.append("# Generated by ProbeFlow xmgrace_export")
    out.append("@version 50121")
    out.append(f"@page size {width_pts}, {height_pts}")
    out.append("@page scroll 5%")
    out.append("@page inout 5%")
    out.append("@link page off")
    # Standard font map (matches Default.agr).
    out.append('@map font 0 to "Times-Roman", "Times-Roman"')
    out.append('@map font 1 to "Times-Italic", "Times-Italic"')
    out.append('@map font 2 to "Times-Bold", "Times-Bold"')
    out.append('@map font 3 to "Times-BoldItalic", "Times-BoldItalic"')
    out.append('@map font 4 to "Helvetica", "Helvetica"')
    out.append('@map font 5 to "Helvetica-Oblique", "Helvetica-Oblique"')
    out.append('@map font 6 to "Helvetica-Bold", "Helvetica-Bold"')
    out.append('@map font 7 to "Helvetica-BoldOblique", "Helvetica-BoldOblique"')
    out.append('@map font 8 to "Courier", "Courier"')
    out.append('@map font 12 to "Symbol", "Symbol"')
    # Standard 16-colour map.
    out.append('@map color 0 to (255, 255, 255), "white"')
    out.append('@map color 1 to (0, 0, 0), "black"')
    out.append('@map color 2 to (255, 0, 0), "red"')
    out.append('@map color 3 to (0, 255, 0), "green"')
    out.append('@map color 4 to (0, 0, 255), "blue"')
    out.append('@map color 8 to (148, 0, 211), "violet"')
    out.append('@map color 9 to (0, 255, 255), "cyan"')
    out.append('@map color 11 to (255, 165, 0), "orange"')
    out.append('@map color 13 to (103, 7, 72), "maroon"')
    out.append('@map color 15 to (0, 139, 0), "green4"')
    out.append(f"@default font {font_idx}")
    out.append("@default char size 1.000000")
    out.append("@background color 0")
    out.append("@page background fill on")

    # ── Graph 0 ──────────────────────────────────────────────────────────────
    out.append("@g0 on")
    out.append("@g0 type XY")
    out.append("@with g0")
    out.append(f"@    world {xmin:.8g}, {ymin:.8g}, {xmax:.8g}, {ymax:.8g}")
    out.append("@    view 0.150000, 0.150000, 1.150000, 0.850000")
    if title:
        out.append(f'@    title "{_grace_escape(title)}"')
        out.append(f"@    title font {font_bold_idx}")
        out.append("@    title size 1.4")
    if subtitle:
        out.append(f'@    subtitle "{_grace_escape(subtitle)}"')
        out.append(f"@    subtitle font {font_idx}")
        out.append("@    subtitle size 1.0")
    # X axis
    out.append(f'@    xaxis  label "{_grace_escape(x_label)}"')
    out.append(f"@    xaxis  label font {font_idx}")
    out.append("@    xaxis  label char size 1.20")
    out.append(f"@    xaxis  ticklabel font {font_idx}")
    out.append("@    xaxis  ticklabel char size 1.00")
    out.append("@    xaxis  tick major linewidth 1.5")
    out.append("@    xaxis  tick minor ticks 1")
    # Y axis
    out.append(f'@    yaxis  label "{_grace_escape(y_label)}"')
    out.append(f"@    yaxis  label font {font_idx}")
    out.append("@    yaxis  label char size 1.20")
    out.append(f"@    yaxis  ticklabel font {font_idx}")
    out.append("@    yaxis  ticklabel char size 1.00")
    out.append("@    yaxis  tick major linewidth 1.5")
    out.append("@    yaxis  tick minor ticks 1")
    # Legend (only if any curve has a legend string)
    has_legend = any(c.legend for c in curves)
    if has_legend:
        out.append("@    legend on")
        out.append("@    legend loctype view")
        out.append("@    legend 0.85, 0.80")
        out.append(f"@    legend font {font_idx}")
        out.append("@    legend char size 0.90")

    # Per-curve style lines.
    for i, c in enumerate(curves):
        col = _CURVE_COLORS[i % len(_CURVE_COLORS)]
        out.append(f"@    s{i} line type 1")
        out.append(f"@    s{i} line linewidth 1.5")
        out.append(f"@    s{i} line color {col}")
        if c.legend:
            out.append(f'@    s{i} legend "{_grace_escape(c.legend)}"')

    # ── Data sections ───────────────────────────────────────────────────────
    for i, c in enumerate(curves):
        y = np.asarray(c.y, dtype=float).ravel()
        if y.shape[0] != x.shape[0]:
            raise ValueError(
                f"curve {c.name!r} has length {y.shape[0]}, expected {x.shape[0]}")
        out.append(f"@target G0.S{i}")
        out.append("@type xy")
        for xv, yv in zip(x, y):
            out.append(f"{xv:.10g} {yv:.10g}")
        out.append("&")

    # Trailing newline so xmgrace doesn't complain about missing EOL.
    return "\n".join(out) + "\n"


def _run_xmgrace(agr_path: Path, out_path: Path, hdevice: str) -> None:
    """Drive xmgrace to render *agr_path* into *out_path* using *hdevice*."""
    binary = shutil.which("xmgrace")
    if binary is None:
        raise FileNotFoundError(
            "xmgrace is not on PATH — install Grace (apt install grace) "
            "or use the matplotlib fallback export.")
    cmd = [
        binary, "-nosafe", "-hardcopy",
        "-hdevice", hdevice,
        "-printfile", str(out_path),
        str(agr_path),
    ]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    # xmgrace can be chatty on stderr while still succeeding; we only fail
    # if the output file wasn't actually created.
    if not out_path.exists() or out_path.stat().st_size == 0:
        raise RuntimeError(
            f"xmgrace failed for {hdevice} export. "
            f"stdout: {res.stdout.strip()!r}  stderr: {res.stderr.strip()!r}")


def _eps_to_pdf(eps_path: Path, pdf_path: Path) -> None:
    """Convert EPS → PDF via ps2pdf."""
    binary = shutil.which("ps2pdf") or shutil.which("ps2pdf14")
    if binary is None:
        raise FileNotFoundError("ps2pdf not found — install ghostscript.")
    res = subprocess.run(
        [binary, str(eps_path), str(pdf_path)],
        capture_output=True, text=True, timeout=30)
    if not pdf_path.exists() or pdf_path.stat().st_size == 0:
        raise RuntimeError(
            f"ps2pdf failed. stdout: {res.stdout.strip()!r}  "
            f"stderr: {res.stderr.strip()!r}")


# ── Top-level helper used by the GUI ─────────────────────────────────────────

def export_bundle(
    out_dir: Path,
    basename: str,
    x: np.ndarray,
    curves: Sequence[Curve],
    *,
    x_label: str,
    y_label: str,
    title: str = "",
    subtitle: str = "",
    font: str = "Helvetica",
) -> dict[str, Path]:
    """Produce ``basename.agr`` + ``basename.png`` + ``basename.pdf`` in
    *out_dir*. Returns a dict mapping format → final path.

    The PDF is produced by rendering EPS first (Grace 5.1's hardcopy device
    list does not include PDF directly) and then running ps2pdf. The
    intermediate EPS file is removed at the end.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    agr_path = out_dir / f"{basename}.agr"
    png_path = out_dir / f"{basename}.png"
    pdf_path = out_dir / f"{basename}.pdf"

    agr_text = build_agr(
        x, curves,
        x_label=x_label, y_label=y_label,
        title=title, subtitle=subtitle, font=font,
    )
    agr_path.write_text(agr_text, encoding="utf-8")

    _run_xmgrace(agr_path, png_path, "PNG")

    with tempfile.TemporaryDirectory() as td:
        eps_path = Path(td) / f"{basename}.eps"
        _run_xmgrace(agr_path, eps_path, "EPS")
        _eps_to_pdf(eps_path, pdf_path)

    return {"agr": agr_path, "png": png_path, "pdf": pdf_path}
